// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nixprotocol/confidential/v1/genesis.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Params               *Params         `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Accounts             []*AccountState `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baf20b8bbc2817a, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *GenesisState) GetAccounts() []*AccountState {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type AccountState struct {
	Address              string                `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Pubkey               []byte                `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	AvailableBalances    []*BalanceEntry       `protobuf:"bytes,4,rep,name=available_balances,json=availableBalances,proto3" json:"available_balances,omitempty"`
	PendingBalances      []*BalanceEntry       `protobuf:"bytes,5,rep,name=pending_balances,json=pendingBalances,proto3" json:"pending_balances,omitempty"`
	PendingIsZero        []*PendingIsZeroEntry `protobuf:"bytes,6,rep,name=pending_is_zero,json=pendingIsZero,proto3" json:"pending_is_zero,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AccountState) Reset()         { *m = AccountState{} }
func (m *AccountState) String() string { return proto.CompactTextString(m) }
func (*AccountState) ProtoMessage()    {}
func (*AccountState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baf20b8bbc2817a, []int{1}
}
func (m *AccountState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountState.Unmarshal(m, b)
}
func (m *AccountState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountState.Marshal(b, m, deterministic)
}
func (m *AccountState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountState.Merge(m, src)
}
func (m *AccountState) XXX_Size() int {
	return xxx_messageInfo_AccountState.Size(m)
}
func (m *AccountState) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountState.DiscardUnknown(m)
}

var xxx_messageInfo_AccountState proto.InternalMessageInfo

func (m *AccountState) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AccountState) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *AccountState) GetAvailableBalances() []*BalanceEntry {
	if m != nil {
		return m.AvailableBalances
	}
	return nil
}

func (m *AccountState) GetPendingBalances() []*BalanceEntry {
	if m != nil {
		return m.PendingBalances
	}
	return nil
}

func (m *AccountState) GetPendingIsZero() []*PendingIsZeroEntry {
	if m != nil {
		return m.PendingIsZero
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "nixprotocol.confidential.v1.GenesisState")
	proto.RegisterType((*AccountState)(nil), "nixprotocol.confidential.v1.AccountState")
}

func init() {
	proto.RegisterFile("nixprotocol/confidential/v1/genesis.proto", fileDescriptor_4baf20b8bbc2817a)
}

var fileDescriptor_4baf20b8bbc2817a = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x33, 0x98, 0x63, 0x16, 0x8c, 0xd8, 0x83, 0x59, 0xf4, 0x42, 0xf0, 0x20, 0x1c, 0xdc,
	0x04, 0x8f, 0x9e, 0x24, 0x21, 0x46, 0x4e, 0x66, 0x9a, 0x68, 0xb8, 0x90, 0x6e, 0x7b, 0x62, 0x63,
	0x69, 0x9b, 0xb6, 0x23, 0xe2, 0xc7, 0xf0, 0xbb, 0xf9, 0x7d, 0x4c, 0xd6, 0x81, 0xbb, 0xb8, 0xe8,
	0xf1, 0xbd, 0xfe, 0xfe, 0xbf, 0xf7, 0xd2, 0x3c, 0x34, 0xe4, 0xf4, 0x5d, 0x2a, 0x61, 0x44, 0x2a,
	0x58, 0x94, 0x0a, 0xfe, 0x42, 0x33, 0xe0, 0x86, 0x12, 0x16, 0xad, 0x47, 0xd1, 0x12, 0x38, 0x68,
	0xaa, 0xc3, 0x02, 0xc0, 0xa7, 0x15, 0x34, 0xac, 0xa2, 0xe1, 0x7a, 0x74, 0x72, 0x5e, 0xe7, 0x31,
	0x1b, 0x09, 0xa5, 0xa5, 0xff, 0xe9, 0xa0, 0xce, 0xad, 0xf5, 0x3e, 0x18, 0x62, 0x00, 0x5f, 0x23,
	0x4f, 0x12, 0x45, 0x56, 0x3a, 0x70, 0x7a, 0xce, 0xa0, 0x3d, 0x3e, 0x0b, 0x6b, 0xe6, 0x84, 0xf7,
	0x05, 0x1a, 0x97, 0x11, 0x3c, 0x45, 0x3e, 0x49, 0x53, 0x91, 0x73, 0xa3, 0x83, 0x46, 0xaf, 0x39,
	0x68, 0x8f, 0x87, 0xb5, 0xf1, 0x1b, 0x0b, 0x17, 0x93, 0xe3, 0x5d, 0xb4, 0xff, 0xd5, 0x40, 0x9d,
	0xea, 0x13, 0x0e, 0x50, 0x8b, 0x64, 0x99, 0x02, 0x6d, 0xb7, 0xda, 0x8f, 0xb7, 0x25, 0x3e, 0x46,
	0x9e, 0xcc, 0x93, 0x37, 0xd8, 0x04, 0x8d, 0x9e, 0x33, 0xe8, 0xc4, 0x65, 0x85, 0x9f, 0x11, 0x26,
	0x6b, 0x42, 0x19, 0x49, 0x18, 0x2c, 0x12, 0xc2, 0x08, 0x4f, 0x41, 0x07, 0xee, 0x1f, 0x76, 0x9a,
	0x58, 0x78, 0xca, 0x8d, 0xda, 0xc4, 0x47, 0x3b, 0x49, 0xd9, 0xd6, 0xf8, 0x11, 0x75, 0x25, 0xf0,
	0x8c, 0xf2, 0xe5, 0x8f, 0x77, 0xef, 0xbf, 0xde, 0xc3, 0x52, 0xb1, 0xb3, 0x3e, 0xa1, 0x6d, 0x6b,
	0x41, 0xf5, 0xe2, 0x03, 0x94, 0x08, 0xbc, 0x42, 0x1a, 0xd5, 0xff, 0xbf, 0xcd, 0xdc, 0xe9, 0x39,
	0x28, 0x61, 0xd5, 0x07, 0xb2, 0xda, 0x9b, 0xb9, 0x7e, 0xb3, 0xeb, 0xce, 0x5c, 0xbf, 0xd5, 0xf5,
	0x27, 0xe3, 0xf9, 0xe5, 0x92, 0x9a, 0xd7, 0x3c, 0x09, 0x53, 0xb1, 0x8a, 0x7e, 0x3b, 0x91, 0x8b,
	0x95, 0xc8, 0x72, 0x06, 0xf6, 0x4c, 0x12, 0xaf, 0x60, 0xae, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xb8, 0xfc, 0xb7, 0x8e, 0x9a, 0x02, 0x00, 0x00,
}
