package types

// This file provides the minimum protobuf compatibility methods (ProtoMessage,
// Reset, String) required by cosmos-sdk's Msg interface. These are normally
// generated by protoc but are hand-written here until .proto definitions are
// added.

import "encoding/json"

// ---------- MsgRegisterKey ----------

func (*MsgRegisterKey) ProtoMessage()    {}
func (m *MsgRegisterKey) Reset()         { *m = MsgRegisterKey{} }
func (m *MsgRegisterKey) String() string { bz, _ := json.Marshal(m); return string(bz) }

// ---------- MsgShield ----------

func (*MsgShield) ProtoMessage()    {}
func (m *MsgShield) Reset()         { *m = MsgShield{} }
func (m *MsgShield) String() string { bz, _ := json.Marshal(m); return string(bz) }

// ---------- MsgConfidentialSend ----------

func (*MsgConfidentialSend) ProtoMessage()    {}
func (m *MsgConfidentialSend) Reset()         { *m = MsgConfidentialSend{} }
func (m *MsgConfidentialSend) String() string { bz, _ := json.Marshal(m); return string(bz) }

// ---------- MsgApplyPending ----------

func (*MsgApplyPending) ProtoMessage()    {}
func (m *MsgApplyPending) Reset()         { *m = MsgApplyPending{} }
func (m *MsgApplyPending) String() string { bz, _ := json.Marshal(m); return string(bz) }

// ---------- MsgUnshield ----------

func (*MsgUnshield) ProtoMessage()    {}
func (m *MsgUnshield) Reset()         { *m = MsgUnshield{} }
func (m *MsgUnshield) String() string { bz, _ := json.Marshal(m); return string(bz) }

// ---------- MsgSetAuditorKey ----------

func (*MsgSetAuditorKey) ProtoMessage()    {}
func (m *MsgSetAuditorKey) Reset()         { *m = MsgSetAuditorKey{} }
func (m *MsgSetAuditorKey) String() string { bz, _ := json.Marshal(m); return string(bz) }

// ---------- MsgRotateKey ----------

func (*MsgRotateKey) ProtoMessage()    {}
func (m *MsgRotateKey) Reset()         { *m = MsgRotateKey{} }
func (m *MsgRotateKey) String() string { bz, _ := json.Marshal(m); return string(bz) }
