// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nixprotocol/confidential/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryBalanceRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Denom                string   `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBalanceRequest) Reset()         { *m = QueryBalanceRequest{} }
func (m *QueryBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBalanceRequest) ProtoMessage()    {}
func (*QueryBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88ced9958953119, []int{0}
}
func (m *QueryBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBalanceRequest.Unmarshal(m, b)
}
func (m *QueryBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBalanceRequest.Marshal(b, m, deterministic)
}
func (m *QueryBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBalanceRequest.Merge(m, src)
}
func (m *QueryBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_QueryBalanceRequest.Size(m)
}
func (m *QueryBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBalanceRequest proto.InternalMessageInfo

func (m *QueryBalanceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryBalanceRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryBalanceResponse struct {
	Available            []byte   `protobuf:"bytes,1,opt,name=available,proto3" json:"available,omitempty"`
	Pending              []byte   `protobuf:"bytes,2,opt,name=pending,proto3" json:"pending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBalanceResponse) Reset()         { *m = QueryBalanceResponse{} }
func (m *QueryBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBalanceResponse) ProtoMessage()    {}
func (*QueryBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88ced9958953119, []int{1}
}
func (m *QueryBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBalanceResponse.Unmarshal(m, b)
}
func (m *QueryBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBalanceResponse.Marshal(b, m, deterministic)
}
func (m *QueryBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBalanceResponse.Merge(m, src)
}
func (m *QueryBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_QueryBalanceResponse.Size(m)
}
func (m *QueryBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBalanceResponse proto.InternalMessageInfo

func (m *QueryBalanceResponse) GetAvailable() []byte {
	if m != nil {
		return m.Available
	}
	return nil
}

func (m *QueryBalanceResponse) GetPending() []byte {
	if m != nil {
		return m.Pending
	}
	return nil
}

type QueryAuditorKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAuditorKeyRequest) Reset()         { *m = QueryAuditorKeyRequest{} }
func (m *QueryAuditorKeyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAuditorKeyRequest) ProtoMessage()    {}
func (*QueryAuditorKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88ced9958953119, []int{2}
}
func (m *QueryAuditorKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAuditorKeyRequest.Unmarshal(m, b)
}
func (m *QueryAuditorKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAuditorKeyRequest.Marshal(b, m, deterministic)
}
func (m *QueryAuditorKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditorKeyRequest.Merge(m, src)
}
func (m *QueryAuditorKeyRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAuditorKeyRequest.Size(m)
}
func (m *QueryAuditorKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditorKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditorKeyRequest proto.InternalMessageInfo

type QueryAuditorKeyResponse struct {
	AuditorPubKey        []byte   `protobuf:"bytes,1,opt,name=auditor_pub_key,json=auditorPubKey,proto3" json:"auditor_pub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAuditorKeyResponse) Reset()         { *m = QueryAuditorKeyResponse{} }
func (m *QueryAuditorKeyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAuditorKeyResponse) ProtoMessage()    {}
func (*QueryAuditorKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88ced9958953119, []int{3}
}
func (m *QueryAuditorKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAuditorKeyResponse.Unmarshal(m, b)
}
func (m *QueryAuditorKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAuditorKeyResponse.Marshal(b, m, deterministic)
}
func (m *QueryAuditorKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditorKeyResponse.Merge(m, src)
}
func (m *QueryAuditorKeyResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAuditorKeyResponse.Size(m)
}
func (m *QueryAuditorKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditorKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditorKeyResponse proto.InternalMessageInfo

func (m *QueryAuditorKeyResponse) GetAuditorPubKey() []byte {
	if m != nil {
		return m.AuditorPubKey
	}
	return nil
}

type QueryParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88ced9958953119, []int{4}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsRequest.Unmarshal(m, b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryParamsRequest.Size(m)
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params               *Params  `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88ced9958953119, []int{5}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsResponse.Unmarshal(m, b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryParamsResponse.Size(m)
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type QueryAccountInfoRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAccountInfoRequest) Reset()         { *m = QueryAccountInfoRequest{} }
func (m *QueryAccountInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAccountInfoRequest) ProtoMessage()    {}
func (*QueryAccountInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88ced9958953119, []int{6}
}
func (m *QueryAccountInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAccountInfoRequest.Unmarshal(m, b)
}
func (m *QueryAccountInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAccountInfoRequest.Marshal(b, m, deterministic)
}
func (m *QueryAccountInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountInfoRequest.Merge(m, src)
}
func (m *QueryAccountInfoRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAccountInfoRequest.Size(m)
}
func (m *QueryAccountInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountInfoRequest proto.InternalMessageInfo

func (m *QueryAccountInfoRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryAccountInfoResponse struct {
	Pubkey               []byte   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	KeyCounter           uint32   `protobuf:"varint,2,opt,name=key_counter,json=keyCounter,proto3" json:"key_counter,omitempty"`
	Registered           bool     `protobuf:"varint,3,opt,name=registered,proto3" json:"registered,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAccountInfoResponse) Reset()         { *m = QueryAccountInfoResponse{} }
func (m *QueryAccountInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAccountInfoResponse) ProtoMessage()    {}
func (*QueryAccountInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88ced9958953119, []int{7}
}
func (m *QueryAccountInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAccountInfoResponse.Unmarshal(m, b)
}
func (m *QueryAccountInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAccountInfoResponse.Marshal(b, m, deterministic)
}
func (m *QueryAccountInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountInfoResponse.Merge(m, src)
}
func (m *QueryAccountInfoResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAccountInfoResponse.Size(m)
}
func (m *QueryAccountInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountInfoResponse proto.InternalMessageInfo

func (m *QueryAccountInfoResponse) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *QueryAccountInfoResponse) GetKeyCounter() uint32 {
	if m != nil {
		return m.KeyCounter
	}
	return 0
}

func (m *QueryAccountInfoResponse) GetRegistered() bool {
	if m != nil {
		return m.Registered
	}
	return false
}

func init() {
	proto.RegisterType((*QueryBalanceRequest)(nil), "nixprotocol.confidential.v1.QueryBalanceRequest")
	proto.RegisterType((*QueryBalanceResponse)(nil), "nixprotocol.confidential.v1.QueryBalanceResponse")
	proto.RegisterType((*QueryAuditorKeyRequest)(nil), "nixprotocol.confidential.v1.QueryAuditorKeyRequest")
	proto.RegisterType((*QueryAuditorKeyResponse)(nil), "nixprotocol.confidential.v1.QueryAuditorKeyResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "nixprotocol.confidential.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "nixprotocol.confidential.v1.QueryParamsResponse")
	proto.RegisterType((*QueryAccountInfoRequest)(nil), "nixprotocol.confidential.v1.QueryAccountInfoRequest")
	proto.RegisterType((*QueryAccountInfoResponse)(nil), "nixprotocol.confidential.v1.QueryAccountInfoResponse")
}

func init() {
	proto.RegisterFile("nixprotocol/confidential/v1/query.proto", fileDescriptor_b88ced9958953119)
}

var fileDescriptor_b88ced9958953119 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0x26, 0x95, 0xdd, 0xda, 0xb3, 0x2d, 0xc2, 0xb8, 0xd4, 0x10, 0x8b, 0x96, 0x14, 0x75, 0x51,
	0x4c, 0xf6, 0x47, 0x8b, 0x20, 0x08, 0xad, 0x78, 0x21, 0x05, 0xa9, 0xb9, 0xf4, 0x66, 0x99, 0x24,
	0xa7, 0xeb, 0xb0, 0xd9, 0x99, 0x34, 0x99, 0x2c, 0x86, 0xd2, 0x1b, 0x5f, 0xc1, 0x1b, 0x5f, 0xc1,
	0x1b, 0x2f, 0xc4, 0x37, 0xf1, 0x15, 0x7c, 0x10, 0xd9, 0x99, 0x09, 0xbb, 0x65, 0x6d, 0xb6, 0x7b,
	0x39, 0x5f, 0xce, 0xf7, 0x33, 0x67, 0x3e, 0x02, 0x4f, 0x38, 0xfb, 0x92, 0x66, 0x42, 0x8a, 0x48,
	0x24, 0x7e, 0x24, 0xf8, 0x19, 0x8b, 0x91, 0x4b, 0x46, 0x13, 0x7f, 0xda, 0xf3, 0xcf, 0x0b, 0xcc,
	0x4a, 0x4f, 0x7d, 0x26, 0xf7, 0x17, 0x06, 0xbd, 0xc5, 0x41, 0x6f, 0xda, 0x73, 0xf6, 0x46, 0x42,
	0x8c, 0x12, 0xf4, 0x69, 0xca, 0x7c, 0xca, 0xb9, 0x90, 0x54, 0x32, 0xc1, 0x73, 0x4d, 0x75, 0x6a,
	0x3d, 0x64, 0x99, 0xa2, 0x19, 0x74, 0xdf, 0xc1, 0xdd, 0x8f, 0x33, 0xcb, 0x63, 0x9a, 0x50, 0x1e,
	0x61, 0x80, 0xe7, 0x05, 0xe6, 0x92, 0xd8, 0xb0, 0x49, 0xe3, 0x38, 0xc3, 0x3c, 0xb7, 0xad, 0x7d,
	0xab, 0xb3, 0x15, 0x54, 0x47, 0xd2, 0x86, 0x46, 0x8c, 0x5c, 0x4c, 0xec, 0x0d, 0x85, 0xeb, 0x83,
	0xfb, 0x01, 0xda, 0x57, 0x65, 0xf2, 0x54, 0xf0, 0x1c, 0xc9, 0x1e, 0x6c, 0xd1, 0x29, 0x65, 0x09,
	0x0d, 0x13, 0x54, 0x4a, 0xdb, 0xc1, 0x1c, 0x98, 0xb9, 0xa4, 0xc8, 0x63, 0xc6, 0x47, 0x4a, 0x6d,
	0x3b, 0xa8, 0x8e, 0xae, 0x0d, 0xbb, 0x4a, 0xef, 0xa8, 0x88, 0x99, 0x14, 0xd9, 0x09, 0x96, 0x26,
	0x99, 0x7b, 0x04, 0xf7, 0x96, 0xbe, 0x18, 0xb3, 0xc7, 0x70, 0x87, 0x6a, 0x74, 0x98, 0x16, 0xe1,
	0x70, 0x8c, 0xa5, 0xb1, 0xdc, 0x31, 0xf0, 0x69, 0x11, 0x9e, 0x60, 0xe9, 0xb6, 0x81, 0x28, 0x89,
	0x53, 0x9a, 0xd1, 0x49, 0x5e, 0x09, 0x07, 0x66, 0x13, 0x15, 0x6a, 0x44, 0x5f, 0x43, 0x33, 0x55,
	0x88, 0xd2, 0x6a, 0xf5, 0x0f, 0xbc, 0x9a, 0x57, 0xf1, 0x0c, 0xd9, 0x50, 0xdc, 0x41, 0x15, 0x36,
	0x8a, 0x44, 0xc1, 0xe5, 0x7b, 0x7e, 0x26, 0x56, 0x6e, 0xd8, 0xcd, 0xc1, 0x5e, 0x26, 0x99, 0x34,
	0xbb, 0xd0, 0x4c, 0x8b, 0x70, 0x7e, 0x33, 0x73, 0x22, 0x0f, 0xa1, 0x35, 0xc6, 0x72, 0xa8, 0x08,
	0x98, 0xa9, 0x6d, 0xee, 0x04, 0x30, 0xc6, 0xf2, 0xad, 0x46, 0xc8, 0x03, 0x80, 0x0c, 0x47, 0x2c,
	0x97, 0x98, 0x61, 0x6c, 0xdf, 0xda, 0xb7, 0x3a, 0xb7, 0x83, 0x05, 0xa4, 0xff, 0xbb, 0x01, 0x0d,
	0xe5, 0x4a, 0x7e, 0x5a, 0xb0, 0x69, 0x9e, 0x91, 0x74, 0x6b, 0x2f, 0xfb, 0x9f, 0xe2, 0x38, 0xbd,
	0x35, 0x18, 0xfa, 0x4e, 0xee, 0x9b, 0xaf, 0x7f, 0xfe, 0x7e, 0xdb, 0x78, 0x45, 0x0e, 0xfd, 0xba,
	0xd2, 0x86, 0x9a, 0xe5, 0x5f, 0x98, 0x35, 0x5d, 0xfa, 0x17, 0xaa, 0x7a, 0x97, 0xe4, 0x87, 0x05,
	0x30, 0x6f, 0x03, 0x19, 0xac, 0x4e, 0xb0, 0xd4, 0x2a, 0xe7, 0xc5, 0x7a, 0x24, 0x93, 0xbc, 0xab,
	0x92, 0x3f, 0x25, 0x9d, 0xda, 0xe4, 0x55, 0x27, 0x67, 0xef, 0xf4, 0xdd, 0x82, 0xa6, 0xee, 0x08,
	0xf1, 0x57, 0x5b, 0x5e, 0x29, 0xa8, 0xd3, 0xbd, 0x39, 0xc1, 0xe4, 0x7b, 0xa6, 0xf2, 0x3d, 0x22,
	0x07, 0xb5, 0xf9, 0x74, 0x57, 0xc9, 0x2f, 0x0b, 0x5a, 0x0b, 0x95, 0x23, 0x37, 0x59, 0xc9, 0x52,
	0xad, 0x9d, 0x97, 0x6b, 0xb2, 0x4c, 0xd2, 0x43, 0x95, 0xb4, 0x4b, 0xbc, 0xfa, 0x4d, 0x6a, 0xe6,
	0xbc, 0x03, 0xc7, 0xfd, 0x4f, 0xdd, 0x11, 0x93, 0x9f, 0x8b, 0xd0, 0x8b, 0xc4, 0xe4, 0x5a, 0xee,
	0xf3, 0x89, 0x88, 0x8b, 0x04, 0xf5, 0x8f, 0x2f, 0x6c, 0xaa, 0x99, 0xc1, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xd7, 0xb7, 0x7b, 0xf6, 0x88, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Balance(ctx context.Context, in *QueryBalanceRequest, opts ...grpc.CallOption) (*QueryBalanceResponse, error)
	AuditorKey(ctx context.Context, in *QueryAuditorKeyRequest, opts ...grpc.CallOption) (*QueryAuditorKeyResponse, error)
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	AccountInfo(ctx context.Context, in *QueryAccountInfoRequest, opts ...grpc.CallOption) (*QueryAccountInfoResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Balance(ctx context.Context, in *QueryBalanceRequest, opts ...grpc.CallOption) (*QueryBalanceResponse, error) {
	out := new(QueryBalanceResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.confidential.v1.Query/Balance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuditorKey(ctx context.Context, in *QueryAuditorKeyRequest, opts ...grpc.CallOption) (*QueryAuditorKeyResponse, error) {
	out := new(QueryAuditorKeyResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.confidential.v1.Query/AuditorKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.confidential.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AccountInfo(ctx context.Context, in *QueryAccountInfoRequest, opts ...grpc.CallOption) (*QueryAccountInfoResponse, error) {
	out := new(QueryAccountInfoResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.confidential.v1.Query/AccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Balance(context.Context, *QueryBalanceRequest) (*QueryBalanceResponse, error)
	AuditorKey(context.Context, *QueryAuditorKeyRequest) (*QueryAuditorKeyResponse, error)
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	AccountInfo(context.Context, *QueryAccountInfoRequest) (*QueryAccountInfoResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Balance(ctx context.Context, req *QueryBalanceRequest) (*QueryBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Balance not implemented")
}
func (*UnimplementedQueryServer) AuditorKey(ctx context.Context, req *QueryAuditorKeyRequest) (*QueryAuditorKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditorKey not implemented")
}
func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AccountInfo(ctx context.Context, req *QueryAccountInfoRequest) (*QueryAccountInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountInfo not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Balance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Balance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.confidential.v1.Query/Balance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Balance(ctx, req.(*QueryBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuditorKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditorKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuditorKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.confidential.v1.Query/AuditorKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuditorKey(ctx, req.(*QueryAuditorKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.confidential.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAccountInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.confidential.v1.Query/AccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AccountInfo(ctx, req.(*QueryAccountInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nixprotocol.confidential.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Balance",
			Handler:    _Query_Balance_Handler,
		},
		{
			MethodName: "AuditorKey",
			Handler:    _Query_AuditorKey_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AccountInfo",
			Handler:    _Query_AccountInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nixprotocol/confidential/v1/query.proto",
}
