// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nixprotocol/confidential/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterKey struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Pubkey               []byte   `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Counter              uint32   `protobuf:"varint,3,opt,name=counter,proto3" json:"counter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRegisterKey) Reset()         { *m = MsgRegisterKey{} }
func (m *MsgRegisterKey) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterKey) ProtoMessage()    {}
func (*MsgRegisterKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{0}
}
func (m *MsgRegisterKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRegisterKey.Unmarshal(m, b)
}
func (m *MsgRegisterKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRegisterKey.Marshal(b, m, deterministic)
}
func (m *MsgRegisterKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterKey.Merge(m, src)
}
func (m *MsgRegisterKey) XXX_Size() int {
	return xxx_messageInfo_MsgRegisterKey.Size(m)
}
func (m *MsgRegisterKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterKey proto.InternalMessageInfo

func (m *MsgRegisterKey) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgRegisterKey) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *MsgRegisterKey) GetCounter() uint32 {
	if m != nil {
		return m.Counter
	}
	return 0
}

type MsgRegisterKeyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRegisterKeyResponse) Reset()         { *m = MsgRegisterKeyResponse{} }
func (m *MsgRegisterKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterKeyResponse) ProtoMessage()    {}
func (*MsgRegisterKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{1}
}
func (m *MsgRegisterKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRegisterKeyResponse.Unmarshal(m, b)
}
func (m *MsgRegisterKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRegisterKeyResponse.Marshal(b, m, deterministic)
}
func (m *MsgRegisterKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterKeyResponse.Merge(m, src)
}
func (m *MsgRegisterKeyResponse) XXX_Size() int {
	return xxx_messageInfo_MsgRegisterKeyResponse.Size(m)
}
func (m *MsgRegisterKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterKeyResponse proto.InternalMessageInfo

type MsgShield struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Denom                string   `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Proof                []byte   `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	EncryptedMemo        []byte   `protobuf:"bytes,6,opt,name=encrypted_memo,json=encryptedMemo,proto3" json:"encrypted_memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgShield) Reset()         { *m = MsgShield{} }
func (m *MsgShield) String() string { return proto.CompactTextString(m) }
func (*MsgShield) ProtoMessage()    {}
func (*MsgShield) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{2}
}
func (m *MsgShield) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgShield.Unmarshal(m, b)
}
func (m *MsgShield) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgShield.Marshal(b, m, deterministic)
}
func (m *MsgShield) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgShield.Merge(m, src)
}
func (m *MsgShield) XXX_Size() int {
	return xxx_messageInfo_MsgShield.Size(m)
}
func (m *MsgShield) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgShield.DiscardUnknown(m)
}

var xxx_messageInfo_MsgShield proto.InternalMessageInfo

func (m *MsgShield) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgShield) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgShield) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgShield) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *MsgShield) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *MsgShield) GetEncryptedMemo() []byte {
	if m != nil {
		return m.EncryptedMemo
	}
	return nil
}

type MsgShieldResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgShieldResponse) Reset()         { *m = MsgShieldResponse{} }
func (m *MsgShieldResponse) String() string { return proto.CompactTextString(m) }
func (*MsgShieldResponse) ProtoMessage()    {}
func (*MsgShieldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{3}
}
func (m *MsgShieldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgShieldResponse.Unmarshal(m, b)
}
func (m *MsgShieldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgShieldResponse.Marshal(b, m, deterministic)
}
func (m *MsgShieldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgShieldResponse.Merge(m, src)
}
func (m *MsgShieldResponse) XXX_Size() int {
	return xxx_messageInfo_MsgShieldResponse.Size(m)
}
func (m *MsgShieldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgShieldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgShieldResponse proto.InternalMessageInfo

type MsgConfidentialSend struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver             string   `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Denom                string   `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	SenderUpdate         []byte   `protobuf:"bytes,4,opt,name=sender_update,json=senderUpdate,proto3" json:"sender_update,omitempty"`
	ReceiverUpdate       []byte   `protobuf:"bytes,5,opt,name=receiver_update,json=receiverUpdate,proto3" json:"receiver_update,omitempty"`
	AuditorUpdate        []byte   `protobuf:"bytes,6,opt,name=auditor_update,json=auditorUpdate,proto3" json:"auditor_update,omitempty"`
	RangeProof           []byte   `protobuf:"bytes,7,opt,name=range_proof,json=rangeProof,proto3" json:"range_proof,omitempty"`
	EqualityProof        []byte   `protobuf:"bytes,8,opt,name=equality_proof,json=equalityProof,proto3" json:"equality_proof,omitempty"`
	ReceiverKeyCounter   uint32   `protobuf:"varint,9,opt,name=receiver_key_counter,json=receiverKeyCounter,proto3" json:"receiver_key_counter,omitempty"`
	EncryptedMemo        []byte   `protobuf:"bytes,10,opt,name=encrypted_memo,json=encryptedMemo,proto3" json:"encrypted_memo,omitempty"`
	AuditorMemo          []byte   `protobuf:"bytes,11,opt,name=auditor_memo,json=auditorMemo,proto3" json:"auditor_memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgConfidentialSend) Reset()         { *m = MsgConfidentialSend{} }
func (m *MsgConfidentialSend) String() string { return proto.CompactTextString(m) }
func (*MsgConfidentialSend) ProtoMessage()    {}
func (*MsgConfidentialSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{4}
}
func (m *MsgConfidentialSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgConfidentialSend.Unmarshal(m, b)
}
func (m *MsgConfidentialSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgConfidentialSend.Marshal(b, m, deterministic)
}
func (m *MsgConfidentialSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfidentialSend.Merge(m, src)
}
func (m *MsgConfidentialSend) XXX_Size() int {
	return xxx_messageInfo_MsgConfidentialSend.Size(m)
}
func (m *MsgConfidentialSend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfidentialSend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfidentialSend proto.InternalMessageInfo

func (m *MsgConfidentialSend) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgConfidentialSend) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *MsgConfidentialSend) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgConfidentialSend) GetSenderUpdate() []byte {
	if m != nil {
		return m.SenderUpdate
	}
	return nil
}

func (m *MsgConfidentialSend) GetReceiverUpdate() []byte {
	if m != nil {
		return m.ReceiverUpdate
	}
	return nil
}

func (m *MsgConfidentialSend) GetAuditorUpdate() []byte {
	if m != nil {
		return m.AuditorUpdate
	}
	return nil
}

func (m *MsgConfidentialSend) GetRangeProof() []byte {
	if m != nil {
		return m.RangeProof
	}
	return nil
}

func (m *MsgConfidentialSend) GetEqualityProof() []byte {
	if m != nil {
		return m.EqualityProof
	}
	return nil
}

func (m *MsgConfidentialSend) GetReceiverKeyCounter() uint32 {
	if m != nil {
		return m.ReceiverKeyCounter
	}
	return 0
}

func (m *MsgConfidentialSend) GetEncryptedMemo() []byte {
	if m != nil {
		return m.EncryptedMemo
	}
	return nil
}

func (m *MsgConfidentialSend) GetAuditorMemo() []byte {
	if m != nil {
		return m.AuditorMemo
	}
	return nil
}

type MsgConfidentialSendResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgConfidentialSendResponse) Reset()         { *m = MsgConfidentialSendResponse{} }
func (m *MsgConfidentialSendResponse) String() string { return proto.CompactTextString(m) }
func (*MsgConfidentialSendResponse) ProtoMessage()    {}
func (*MsgConfidentialSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{5}
}
func (m *MsgConfidentialSendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgConfidentialSendResponse.Unmarshal(m, b)
}
func (m *MsgConfidentialSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgConfidentialSendResponse.Marshal(b, m, deterministic)
}
func (m *MsgConfidentialSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfidentialSendResponse.Merge(m, src)
}
func (m *MsgConfidentialSendResponse) XXX_Size() int {
	return xxx_messageInfo_MsgConfidentialSendResponse.Size(m)
}
func (m *MsgConfidentialSendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfidentialSendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfidentialSendResponse proto.InternalMessageInfo

type MsgApplyPending struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Denom                string   `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	NewAvailableUpdate   []byte   `protobuf:"bytes,3,opt,name=new_available_update,json=newAvailableUpdate,proto3" json:"new_available_update,omitempty"`
	Proof                []byte   `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgApplyPending) Reset()         { *m = MsgApplyPending{} }
func (m *MsgApplyPending) String() string { return proto.CompactTextString(m) }
func (*MsgApplyPending) ProtoMessage()    {}
func (*MsgApplyPending) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{6}
}
func (m *MsgApplyPending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgApplyPending.Unmarshal(m, b)
}
func (m *MsgApplyPending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgApplyPending.Marshal(b, m, deterministic)
}
func (m *MsgApplyPending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApplyPending.Merge(m, src)
}
func (m *MsgApplyPending) XXX_Size() int {
	return xxx_messageInfo_MsgApplyPending.Size(m)
}
func (m *MsgApplyPending) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApplyPending.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApplyPending proto.InternalMessageInfo

func (m *MsgApplyPending) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgApplyPending) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgApplyPending) GetNewAvailableUpdate() []byte {
	if m != nil {
		return m.NewAvailableUpdate
	}
	return nil
}

func (m *MsgApplyPending) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type MsgApplyPendingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgApplyPendingResponse) Reset()         { *m = MsgApplyPendingResponse{} }
func (m *MsgApplyPendingResponse) String() string { return proto.CompactTextString(m) }
func (*MsgApplyPendingResponse) ProtoMessage()    {}
func (*MsgApplyPendingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{7}
}
func (m *MsgApplyPendingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgApplyPendingResponse.Unmarshal(m, b)
}
func (m *MsgApplyPendingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgApplyPendingResponse.Marshal(b, m, deterministic)
}
func (m *MsgApplyPendingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApplyPendingResponse.Merge(m, src)
}
func (m *MsgApplyPendingResponse) XXX_Size() int {
	return xxx_messageInfo_MsgApplyPendingResponse.Size(m)
}
func (m *MsgApplyPendingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApplyPendingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApplyPendingResponse proto.InternalMessageInfo

type MsgUnshield struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Denom                string   `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	RangeProof           []byte   `protobuf:"bytes,5,opt,name=range_proof,json=rangeProof,proto3" json:"range_proof,omitempty"`
	DecryptionProof      []byte   `protobuf:"bytes,6,opt,name=decryption_proof,json=decryptionProof,proto3" json:"decryption_proof,omitempty"`
	EncryptedMemo        []byte   `protobuf:"bytes,7,opt,name=encrypted_memo,json=encryptedMemo,proto3" json:"encrypted_memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUnshield) Reset()         { *m = MsgUnshield{} }
func (m *MsgUnshield) String() string { return proto.CompactTextString(m) }
func (*MsgUnshield) ProtoMessage()    {}
func (*MsgUnshield) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{8}
}
func (m *MsgUnshield) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUnshield.Unmarshal(m, b)
}
func (m *MsgUnshield) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUnshield.Marshal(b, m, deterministic)
}
func (m *MsgUnshield) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnshield.Merge(m, src)
}
func (m *MsgUnshield) XXX_Size() int {
	return xxx_messageInfo_MsgUnshield.Size(m)
}
func (m *MsgUnshield) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnshield.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnshield proto.InternalMessageInfo

func (m *MsgUnshield) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgUnshield) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgUnshield) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgUnshield) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *MsgUnshield) GetRangeProof() []byte {
	if m != nil {
		return m.RangeProof
	}
	return nil
}

func (m *MsgUnshield) GetDecryptionProof() []byte {
	if m != nil {
		return m.DecryptionProof
	}
	return nil
}

func (m *MsgUnshield) GetEncryptedMemo() []byte {
	if m != nil {
		return m.EncryptedMemo
	}
	return nil
}

type MsgUnshieldResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUnshieldResponse) Reset()         { *m = MsgUnshieldResponse{} }
func (m *MsgUnshieldResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnshieldResponse) ProtoMessage()    {}
func (*MsgUnshieldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{9}
}
func (m *MsgUnshieldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUnshieldResponse.Unmarshal(m, b)
}
func (m *MsgUnshieldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUnshieldResponse.Marshal(b, m, deterministic)
}
func (m *MsgUnshieldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnshieldResponse.Merge(m, src)
}
func (m *MsgUnshieldResponse) XXX_Size() int {
	return xxx_messageInfo_MsgUnshieldResponse.Size(m)
}
func (m *MsgUnshieldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnshieldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnshieldResponse proto.InternalMessageInfo

type MsgSetAuditorKey struct {
	Authority            string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Pubkey               []byte   `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSetAuditorKey) Reset()         { *m = MsgSetAuditorKey{} }
func (m *MsgSetAuditorKey) String() string { return proto.CompactTextString(m) }
func (*MsgSetAuditorKey) ProtoMessage()    {}
func (*MsgSetAuditorKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{10}
}
func (m *MsgSetAuditorKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSetAuditorKey.Unmarshal(m, b)
}
func (m *MsgSetAuditorKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSetAuditorKey.Marshal(b, m, deterministic)
}
func (m *MsgSetAuditorKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetAuditorKey.Merge(m, src)
}
func (m *MsgSetAuditorKey) XXX_Size() int {
	return xxx_messageInfo_MsgSetAuditorKey.Size(m)
}
func (m *MsgSetAuditorKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetAuditorKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetAuditorKey proto.InternalMessageInfo

func (m *MsgSetAuditorKey) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetAuditorKey) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type MsgSetAuditorKeyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSetAuditorKeyResponse) Reset()         { *m = MsgSetAuditorKeyResponse{} }
func (m *MsgSetAuditorKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetAuditorKeyResponse) ProtoMessage()    {}
func (*MsgSetAuditorKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{11}
}
func (m *MsgSetAuditorKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSetAuditorKeyResponse.Unmarshal(m, b)
}
func (m *MsgSetAuditorKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSetAuditorKeyResponse.Marshal(b, m, deterministic)
}
func (m *MsgSetAuditorKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetAuditorKeyResponse.Merge(m, src)
}
func (m *MsgSetAuditorKeyResponse) XXX_Size() int {
	return xxx_messageInfo_MsgSetAuditorKeyResponse.Size(m)
}
func (m *MsgSetAuditorKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetAuditorKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetAuditorKeyResponse proto.InternalMessageInfo

type MsgRotateKey struct {
	Sender               string             `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	NewPubkey            []byte             `protobuf:"bytes,2,opt,name=new_pubkey,json=newPubkey,proto3" json:"new_pubkey,omitempty"`
	NewCounter           uint32             `protobuf:"varint,3,opt,name=new_counter,json=newCounter,proto3" json:"new_counter,omitempty"`
	ReEncryptedAvailable []*DenomCiphertext `protobuf:"bytes,4,rep,name=re_encrypted_available,json=reEncryptedAvailable,proto3" json:"re_encrypted_available,omitempty"`
	EqualityProofs       []*DenomProof      `protobuf:"bytes,5,rep,name=equality_proofs,json=equalityProofs,proto3" json:"equality_proofs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MsgRotateKey) Reset()         { *m = MsgRotateKey{} }
func (m *MsgRotateKey) String() string { return proto.CompactTextString(m) }
func (*MsgRotateKey) ProtoMessage()    {}
func (*MsgRotateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{12}
}
func (m *MsgRotateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRotateKey.Unmarshal(m, b)
}
func (m *MsgRotateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRotateKey.Marshal(b, m, deterministic)
}
func (m *MsgRotateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRotateKey.Merge(m, src)
}
func (m *MsgRotateKey) XXX_Size() int {
	return xxx_messageInfo_MsgRotateKey.Size(m)
}
func (m *MsgRotateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRotateKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRotateKey proto.InternalMessageInfo

func (m *MsgRotateKey) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgRotateKey) GetNewPubkey() []byte {
	if m != nil {
		return m.NewPubkey
	}
	return nil
}

func (m *MsgRotateKey) GetNewCounter() uint32 {
	if m != nil {
		return m.NewCounter
	}
	return 0
}

func (m *MsgRotateKey) GetReEncryptedAvailable() []*DenomCiphertext {
	if m != nil {
		return m.ReEncryptedAvailable
	}
	return nil
}

func (m *MsgRotateKey) GetEqualityProofs() []*DenomProof {
	if m != nil {
		return m.EqualityProofs
	}
	return nil
}

type MsgRotateKeyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRotateKeyResponse) Reset()         { *m = MsgRotateKeyResponse{} }
func (m *MsgRotateKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRotateKeyResponse) ProtoMessage()    {}
func (*MsgRotateKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6e2a79da74eb02, []int{13}
}
func (m *MsgRotateKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRotateKeyResponse.Unmarshal(m, b)
}
func (m *MsgRotateKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRotateKeyResponse.Marshal(b, m, deterministic)
}
func (m *MsgRotateKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRotateKeyResponse.Merge(m, src)
}
func (m *MsgRotateKeyResponse) XXX_Size() int {
	return xxx_messageInfo_MsgRotateKeyResponse.Size(m)
}
func (m *MsgRotateKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRotateKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRotateKeyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterKey)(nil), "nixprotocol.confidential.v1.MsgRegisterKey")
	proto.RegisterType((*MsgRegisterKeyResponse)(nil), "nixprotocol.confidential.v1.MsgRegisterKeyResponse")
	proto.RegisterType((*MsgShield)(nil), "nixprotocol.confidential.v1.MsgShield")
	proto.RegisterType((*MsgShieldResponse)(nil), "nixprotocol.confidential.v1.MsgShieldResponse")
	proto.RegisterType((*MsgConfidentialSend)(nil), "nixprotocol.confidential.v1.MsgConfidentialSend")
	proto.RegisterType((*MsgConfidentialSendResponse)(nil), "nixprotocol.confidential.v1.MsgConfidentialSendResponse")
	proto.RegisterType((*MsgApplyPending)(nil), "nixprotocol.confidential.v1.MsgApplyPending")
	proto.RegisterType((*MsgApplyPendingResponse)(nil), "nixprotocol.confidential.v1.MsgApplyPendingResponse")
	proto.RegisterType((*MsgUnshield)(nil), "nixprotocol.confidential.v1.MsgUnshield")
	proto.RegisterType((*MsgUnshieldResponse)(nil), "nixprotocol.confidential.v1.MsgUnshieldResponse")
	proto.RegisterType((*MsgSetAuditorKey)(nil), "nixprotocol.confidential.v1.MsgSetAuditorKey")
	proto.RegisterType((*MsgSetAuditorKeyResponse)(nil), "nixprotocol.confidential.v1.MsgSetAuditorKeyResponse")
	proto.RegisterType((*MsgRotateKey)(nil), "nixprotocol.confidential.v1.MsgRotateKey")
	proto.RegisterType((*MsgRotateKeyResponse)(nil), "nixprotocol.confidential.v1.MsgRotateKeyResponse")
}

func init() {
	proto.RegisterFile("nixprotocol/confidential/v1/tx.proto", fileDescriptor_7f6e2a79da74eb02)
}

var fileDescriptor_7f6e2a79da74eb02 = []byte{
	// 874 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcd, 0x72, 0xdb, 0x54,
	0x14, 0x1e, 0xd7, 0xb1, 0x13, 0x1f, 0x3b, 0x4e, 0x50, 0x4d, 0x2a, 0x54, 0x4a, 0x43, 0xa0, 0xc4,
	0x2d, 0xad, 0xed, 0xa4, 0x30, 0xc3, 0x74, 0x17, 0x02, 0xab, 0x8e, 0x67, 0x3c, 0xea, 0x74, 0x86,
	0x61, 0x63, 0x64, 0xeb, 0x44, 0xd1, 0xd4, 0xba, 0x57, 0xe8, 0x5e, 0x25, 0xd1, 0x86, 0x61, 0x78,
	0x06, 0xb6, 0x2c, 0x59, 0xb0, 0xeb, 0x9e, 0x07, 0xca, 0x03, 0xf0, 0x02, 0x8c, 0xee, 0x9f, 0xa5,
	0x24, 0x8e, 0xe3, 0x4d, 0x97, 0xf7, 0x9c, 0xef, 0x9c, 0xef, 0xfc, 0x4b, 0xf0, 0x25, 0x09, 0x2f,
	0xe2, 0x84, 0x72, 0x3a, 0xa5, 0xb3, 0xfe, 0x94, 0x92, 0x93, 0xd0, 0x47, 0xc2, 0x43, 0x6f, 0xd6,
	0x3f, 0x3b, 0xe8, 0xf3, 0x8b, 0x9e, 0xd0, 0x59, 0x0f, 0x0b, 0xa8, 0x5e, 0x11, 0xd5, 0x3b, 0x3b,
	0x70, 0x1e, 0x4c, 0x29, 0x8b, 0x28, 0xeb, 0x47, 0x2c, 0xc8, 0x8d, 0x22, 0x16, 0x48, 0x2b, 0x67,
	0xff, 0x56, 0xdf, 0x59, 0x8c, 0x4c, 0x02, 0xf7, 0x02, 0x68, 0x0f, 0x59, 0xe0, 0x62, 0x10, 0x32,
	0x8e, 0xc9, 0x6b, 0xcc, 0xac, 0x1d, 0xa8, 0x33, 0x24, 0x3e, 0x26, 0x76, 0x65, 0xb7, 0xd2, 0x6d,
	0xb8, 0xea, 0x95, 0xcb, 0xe3, 0x74, 0xf2, 0x0e, 0x33, 0xfb, 0xde, 0x6e, 0xa5, 0xdb, 0x72, 0xd5,
	0xcb, 0xb2, 0x61, 0x7d, 0x4a, 0x53, 0xc2, 0x31, 0xb1, 0xab, 0xbb, 0x95, 0xee, 0xa6, 0xab, 0x9f,
	0xaf, 0x9a, 0x7f, 0x5c, 0xbe, 0x7f, 0xa6, 0xcc, 0xf7, 0x6c, 0xd8, 0x29, 0x13, 0xb9, 0xc8, 0x62,
	0x4a, 0x18, 0xee, 0xfd, 0x5b, 0x81, 0xc6, 0x90, 0x05, 0x6f, 0x4e, 0x43, 0x9c, 0xf9, 0x0b, 0xe9,
	0x3b, 0x50, 0xf3, 0x91, 0xd0, 0x48, 0xb0, 0x37, 0x5c, 0xf9, 0xc8, 0xd1, 0x5e, 0x94, 0xd3, 0x09,
	0xee, 0x86, 0xab, 0x5e, 0xd6, 0x67, 0x00, 0xd3, 0x30, 0x3e, 0xc5, 0x84, 0xe3, 0x05, 0xb7, 0xd7,
	0x44, 0xc0, 0x05, 0x49, 0xee, 0x2d, 0x4e, 0x28, 0x3d, 0xb1, 0x6b, 0x42, 0x25, 0x1f, 0xd6, 0x13,
	0x68, 0x23, 0x99, 0x26, 0x59, 0xcc, 0xd1, 0x1f, 0x47, 0x18, 0x51, 0xbb, 0x2e, 0xd4, 0x9b, 0x46,
	0x3a, 0xc4, 0x88, 0x96, 0xf3, 0xba, 0x0f, 0x1f, 0x99, 0xe0, 0x4d, 0x4a, 0x7f, 0x57, 0xe1, 0xfe,
	0x90, 0x05, 0xc7, 0x85, 0xc2, 0xbf, 0x41, 0xb2, 0x38, 0x39, 0x07, 0x36, 0x12, 0x9c, 0x62, 0x78,
	0x86, 0x89, 0xca, 0xcf, 0xbc, 0xe7, 0x89, 0x57, 0x8b, 0x89, 0x7f, 0x01, 0x9b, 0xd2, 0x76, 0x9c,
	0xc6, 0xbe, 0xc7, 0x51, 0xe5, 0xd8, 0x92, 0xc2, 0xb7, 0x42, 0x66, 0xed, 0xc3, 0x96, 0x76, 0xa3,
	0x61, 0x32, 0xdf, 0xb6, 0x16, 0x2b, 0xe0, 0x13, 0x68, 0x7b, 0xa9, 0x1f, 0x72, 0x6a, 0x70, 0x2a,
	0x71, 0x25, 0x55, 0xb0, 0xc7, 0xd0, 0x4c, 0x3c, 0x12, 0xe0, 0x58, 0xd6, 0x6e, 0x5d, 0x96, 0x55,
	0x88, 0x46, 0xa6, 0x80, 0xbf, 0xa6, 0xde, 0x2c, 0xe4, 0x99, 0xc2, 0x6c, 0xa8, 0x02, 0x2a, 0xa9,
	0x84, 0x0d, 0xa0, 0x63, 0xe2, 0x7a, 0x87, 0xd9, 0x58, 0xcf, 0x4f, 0x43, 0xcc, 0x8f, 0xa5, 0x75,
	0xaf, 0x31, 0x3b, 0x96, 0x9a, 0x1b, 0x3a, 0x03, 0x37, 0x74, 0xc6, 0xfa, 0x1c, 0x5a, 0x3a, 0x0f,
	0x01, 0x6a, 0x0a, 0x50, 0x53, 0xc9, 0xae, 0x37, 0xef, 0x11, 0x3c, 0xbc, 0xa1, 0x4d, 0xa6, 0x8d,
	0x7f, 0x56, 0x60, 0x6b, 0xc8, 0x82, 0xa3, 0x38, 0x9e, 0x65, 0x23, 0x24, 0x7e, 0x48, 0x82, 0x15,
	0xe7, 0x73, 0x00, 0x1d, 0x82, 0xe7, 0x63, 0xef, 0xcc, 0x0b, 0x67, 0xde, 0x64, 0x86, 0xba, 0xbc,
	0x55, 0x11, 0x98, 0x45, 0xf0, 0xfc, 0x48, 0xab, 0x54, 0x8d, 0xcd, 0x64, 0xae, 0x15, 0x26, 0xb3,
	0x1c, 0xf5, 0x27, 0xf0, 0xe0, 0x4a, 0x54, 0x26, 0xe2, 0xff, 0x2a, 0xd0, 0x1c, 0xb2, 0xe0, 0x2d,
	0x61, 0x1f, 0x72, 0x9b, 0xae, 0xcc, 0x45, 0xed, 0xda, 0x5c, 0x3c, 0x85, 0x6d, 0x1f, 0x45, 0xa3,
	0x42, 0x4a, 0x14, 0x4a, 0x4e, 0xd8, 0xd6, 0x5c, 0x3e, 0x5a, 0xb0, 0x83, 0xeb, 0x4b, 0x77, 0xf0,
	0x63, 0xb1, 0x6d, 0x3a, 0x69, 0x53, 0x8c, 0x9f, 0x60, 0x3b, 0x5f, 0x4d, 0xe4, 0x47, 0xb2, 0xff,
	0xf9, 0x75, 0xfb, 0x14, 0x1a, 0x5e, 0xca, 0x4f, 0x69, 0x12, 0xf2, 0x4c, 0xd5, 0x64, 0x2e, 0x58,
	0x74, 0xe3, 0x5e, 0xb5, 0x73, 0xb6, 0x39, 0x6e, 0xcf, 0x01, 0xfb, 0xaa, 0x67, 0xc3, 0xfa, 0xcf,
	0x3d, 0x68, 0xe5, 0x97, 0x8e, 0x72, 0x8f, 0xe3, 0x6d, 0x07, 0xf5, 0x11, 0x40, 0x3e, 0x1b, 0x25,
	0xc2, 0x06, 0xc1, 0xf3, 0x91, 0xbc, 0xab, 0x8f, 0xa1, 0x99, 0xab, 0xcb, 0xb7, 0x35, 0xb7, 0xd0,
	0x3b, 0x31, 0x81, 0x9d, 0x04, 0xc7, 0xf3, 0x62, 0x99, 0x21, 0xb3, 0xd7, 0x76, 0xab, 0xdd, 0xe6,
	0xe1, 0xf3, 0xde, 0x2d, 0x9f, 0x8e, 0xde, 0x0f, 0x79, 0xc7, 0x8f, 0x4d, 0x0f, 0xdd, 0x4e, 0x82,
	0x3f, 0x6a, 0x57, 0x66, 0x26, 0xad, 0x11, 0x6c, 0x95, 0x17, 0x9a, 0xd9, 0x35, 0xe1, 0x7c, 0x7f,
	0xb9, 0x73, 0xd1, 0x4f, 0xb7, 0x5d, 0x5a, 0x7d, 0x56, 0x6e, 0xdc, 0x0e, 0x74, 0x8a, 0xa5, 0xd2,
	0x35, 0x3c, 0xfc, 0xab, 0x0e, 0xd5, 0x21, 0x0b, 0x2c, 0x0a, 0xcd, 0xe2, 0xa7, 0xe9, 0xeb, 0x5b,
	0x49, 0xcb, 0x9f, 0x17, 0xe7, 0xe5, 0x0a, 0x60, 0x4d, 0x6c, 0xfd, 0x02, 0x75, 0xf5, 0x1d, 0xfa,
	0x6a, 0x99, 0xb9, 0xc4, 0x39, 0xbd, 0xbb, 0xe1, 0x0c, 0xc3, 0x6f, 0xb0, 0x7d, 0xed, 0xb3, 0x30,
	0x58, 0xe6, 0xe3, 0xaa, 0x85, 0xf3, 0xdd, 0xaa, 0x16, 0x86, 0x3f, 0x81, 0x56, 0xe9, 0x9e, 0x3d,
	0x5f, 0xe6, 0xa9, 0x88, 0x76, 0xbe, 0x59, 0x05, 0x6d, 0x38, 0x4f, 0x60, 0xc3, 0x5c, 0xa4, 0xee,
	0x32, 0x0f, 0x1a, 0xe9, 0x0c, 0xee, 0x8a, 0x34, 0x3c, 0x29, 0x6c, 0x96, 0xb7, 0xfd, 0xc5, 0xd2,
	0xe6, 0x14, 0xe1, 0xce, 0xb7, 0x2b, 0xc1, 0x0d, 0x6d, 0x08, 0x8d, 0xf9, 0xb6, 0x3f, 0x5d, 0x3a,
	0x76, 0x1a, 0xea, 0x1c, 0xdc, 0x19, 0xaa, 0xa9, 0x9c, 0xda, 0xef, 0x97, 0xef, 0x9f, 0x55, 0xbe,
	0x3f, 0xfc, 0x79, 0x10, 0x84, 0xfc, 0x34, 0x9d, 0xf4, 0xa6, 0x34, 0xea, 0x2f, 0xfa, 0xd7, 0x7b,
	0x11, 0x51, 0x3f, 0x9d, 0xa1, 0xfc, 0xdf, 0x9b, 0xd4, 0x05, 0xe6, 0xe5, 0xff, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x55, 0x44, 0x0d, 0xd8, 0x77, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RegisterKey(ctx context.Context, in *MsgRegisterKey, opts ...grpc.CallOption) (*MsgRegisterKeyResponse, error)
	Shield(ctx context.Context, in *MsgShield, opts ...grpc.CallOption) (*MsgShieldResponse, error)
	ConfidentialSend(ctx context.Context, in *MsgConfidentialSend, opts ...grpc.CallOption) (*MsgConfidentialSendResponse, error)
	ApplyPending(ctx context.Context, in *MsgApplyPending, opts ...grpc.CallOption) (*MsgApplyPendingResponse, error)
	Unshield(ctx context.Context, in *MsgUnshield, opts ...grpc.CallOption) (*MsgUnshieldResponse, error)
	SetAuditorKey(ctx context.Context, in *MsgSetAuditorKey, opts ...grpc.CallOption) (*MsgSetAuditorKeyResponse, error)
	RotateKey(ctx context.Context, in *MsgRotateKey, opts ...grpc.CallOption) (*MsgRotateKeyResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterKey(ctx context.Context, in *MsgRegisterKey, opts ...grpc.CallOption) (*MsgRegisterKeyResponse, error) {
	out := new(MsgRegisterKeyResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.confidential.v1.Msg/RegisterKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Shield(ctx context.Context, in *MsgShield, opts ...grpc.CallOption) (*MsgShieldResponse, error) {
	out := new(MsgShieldResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.confidential.v1.Msg/Shield", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ConfidentialSend(ctx context.Context, in *MsgConfidentialSend, opts ...grpc.CallOption) (*MsgConfidentialSendResponse, error) {
	out := new(MsgConfidentialSendResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.confidential.v1.Msg/ConfidentialSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ApplyPending(ctx context.Context, in *MsgApplyPending, opts ...grpc.CallOption) (*MsgApplyPendingResponse, error) {
	out := new(MsgApplyPendingResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.confidential.v1.Msg/ApplyPending", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Unshield(ctx context.Context, in *MsgUnshield, opts ...grpc.CallOption) (*MsgUnshieldResponse, error) {
	out := new(MsgUnshieldResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.confidential.v1.Msg/Unshield", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetAuditorKey(ctx context.Context, in *MsgSetAuditorKey, opts ...grpc.CallOption) (*MsgSetAuditorKeyResponse, error) {
	out := new(MsgSetAuditorKeyResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.confidential.v1.Msg/SetAuditorKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RotateKey(ctx context.Context, in *MsgRotateKey, opts ...grpc.CallOption) (*MsgRotateKeyResponse, error) {
	out := new(MsgRotateKeyResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.confidential.v1.Msg/RotateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RegisterKey(context.Context, *MsgRegisterKey) (*MsgRegisterKeyResponse, error)
	Shield(context.Context, *MsgShield) (*MsgShieldResponse, error)
	ConfidentialSend(context.Context, *MsgConfidentialSend) (*MsgConfidentialSendResponse, error)
	ApplyPending(context.Context, *MsgApplyPending) (*MsgApplyPendingResponse, error)
	Unshield(context.Context, *MsgUnshield) (*MsgUnshieldResponse, error)
	SetAuditorKey(context.Context, *MsgSetAuditorKey) (*MsgSetAuditorKeyResponse, error)
	RotateKey(context.Context, *MsgRotateKey) (*MsgRotateKeyResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterKey(ctx context.Context, req *MsgRegisterKey) (*MsgRegisterKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterKey not implemented")
}
func (*UnimplementedMsgServer) Shield(ctx context.Context, req *MsgShield) (*MsgShieldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shield not implemented")
}
func (*UnimplementedMsgServer) ConfidentialSend(ctx context.Context, req *MsgConfidentialSend) (*MsgConfidentialSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfidentialSend not implemented")
}
func (*UnimplementedMsgServer) ApplyPending(ctx context.Context, req *MsgApplyPending) (*MsgApplyPendingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPending not implemented")
}
func (*UnimplementedMsgServer) Unshield(ctx context.Context, req *MsgUnshield) (*MsgUnshieldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unshield not implemented")
}
func (*UnimplementedMsgServer) SetAuditorKey(ctx context.Context, req *MsgSetAuditorKey) (*MsgSetAuditorKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAuditorKey not implemented")
}
func (*UnimplementedMsgServer) RotateKey(ctx context.Context, req *MsgRotateKey) (*MsgRotateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateKey not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.confidential.v1.Msg/RegisterKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterKey(ctx, req.(*MsgRegisterKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Shield_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgShield)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Shield(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.confidential.v1.Msg/Shield",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Shield(ctx, req.(*MsgShield))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ConfidentialSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConfidentialSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConfidentialSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.confidential.v1.Msg/ConfidentialSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConfidentialSend(ctx, req.(*MsgConfidentialSend))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ApplyPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgApplyPending)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ApplyPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.confidential.v1.Msg/ApplyPending",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ApplyPending(ctx, req.(*MsgApplyPending))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Unshield_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnshield)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Unshield(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.confidential.v1.Msg/Unshield",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Unshield(ctx, req.(*MsgUnshield))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetAuditorKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetAuditorKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetAuditorKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.confidential.v1.Msg/SetAuditorKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetAuditorKey(ctx, req.(*MsgSetAuditorKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RotateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRotateKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RotateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.confidential.v1.Msg/RotateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RotateKey(ctx, req.(*MsgRotateKey))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nixprotocol.confidential.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterKey",
			Handler:    _Msg_RegisterKey_Handler,
		},
		{
			MethodName: "Shield",
			Handler:    _Msg_Shield_Handler,
		},
		{
			MethodName: "ConfidentialSend",
			Handler:    _Msg_ConfidentialSend_Handler,
		},
		{
			MethodName: "ApplyPending",
			Handler:    _Msg_ApplyPending_Handler,
		},
		{
			MethodName: "Unshield",
			Handler:    _Msg_Unshield_Handler,
		},
		{
			MethodName: "SetAuditorKey",
			Handler:    _Msg_SetAuditorKey_Handler,
		},
		{
			MethodName: "RotateKey",
			Handler:    _Msg_RotateKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nixprotocol/confidential/v1/tx.proto",
}
