// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nixprotocol/confidential/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the module parameters.
type Params struct {
	AuditorPubKey         []byte   `protobuf:"bytes,1,opt,name=auditor_pub_key,json=auditorPubKey,proto3" json:"auditor_pub_key,omitempty"`
	PrevAuditorPubKey     []byte   `protobuf:"bytes,2,opt,name=prev_auditor_pub_key,json=prevAuditorPubKey,proto3" json:"prev_auditor_pub_key,omitempty"`
	AuditorRotationHeight uint64   `protobuf:"varint,3,opt,name=auditor_rotation_height,json=auditorRotationHeight,proto3" json:"auditor_rotation_height,omitempty"`
	AuditorKeyGracePeriod uint64   `protobuf:"varint,4,opt,name=auditor_key_grace_period,json=auditorKeyGracePeriod,proto3" json:"auditor_key_grace_period,omitempty"`
	EnabledDenoms         []string `protobuf:"bytes,5,rep,name=enabled_denoms,json=enabledDenoms,proto3" json:"enabled_denoms,omitempty"`
	MaxTransferBits       int32    `protobuf:"varint,6,opt,name=max_transfer_bits,json=maxTransferBits,proto3" json:"max_transfer_bits,omitempty"`
	RotationCooldown      uint64   `protobuf:"varint,7,opt,name=rotation_cooldown,json=rotationCooldown,proto3" json:"rotation_cooldown,omitempty"`
	MaxMemoSize           int32    `protobuf:"varint,8,opt,name=max_memo_size,json=maxMemoSize,proto3" json:"max_memo_size,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebb505dd6f9ccdd, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAuditorPubKey() []byte {
	if m != nil {
		return m.AuditorPubKey
	}
	return nil
}

func (m *Params) GetPrevAuditorPubKey() []byte {
	if m != nil {
		return m.PrevAuditorPubKey
	}
	return nil
}

func (m *Params) GetAuditorRotationHeight() uint64 {
	if m != nil {
		return m.AuditorRotationHeight
	}
	return 0
}

func (m *Params) GetAuditorKeyGracePeriod() uint64 {
	if m != nil {
		return m.AuditorKeyGracePeriod
	}
	return 0
}

func (m *Params) GetEnabledDenoms() []string {
	if m != nil {
		return m.EnabledDenoms
	}
	return nil
}

func (m *Params) GetMaxTransferBits() int32 {
	if m != nil {
		return m.MaxTransferBits
	}
	return 0
}

func (m *Params) GetRotationCooldown() uint64 {
	if m != nil {
		return m.RotationCooldown
	}
	return 0
}

func (m *Params) GetMaxMemoSize() int32 {
	if m != nil {
		return m.MaxMemoSize
	}
	return 0
}

// BalanceEntry stores a ciphertext balance for a denomination.
type BalanceEntry struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceEntry) Reset()         { *m = BalanceEntry{} }
func (m *BalanceEntry) String() string { return proto.CompactTextString(m) }
func (*BalanceEntry) ProtoMessage()    {}
func (*BalanceEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebb505dd6f9ccdd, []int{1}
}
func (m *BalanceEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceEntry.Unmarshal(m, b)
}
func (m *BalanceEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceEntry.Marshal(b, m, deterministic)
}
func (m *BalanceEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceEntry.Merge(m, src)
}
func (m *BalanceEntry) XXX_Size() int {
	return xxx_messageInfo_BalanceEntry.Size(m)
}
func (m *BalanceEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceEntry.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceEntry proto.InternalMessageInfo

func (m *BalanceEntry) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *BalanceEntry) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

// PendingIsZeroEntry tracks whether a denom's pending balance is zero.
type PendingIsZeroEntry struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	IsZero               bool     `protobuf:"varint,2,opt,name=is_zero,json=isZero,proto3" json:"is_zero,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingIsZeroEntry) Reset()         { *m = PendingIsZeroEntry{} }
func (m *PendingIsZeroEntry) String() string { return proto.CompactTextString(m) }
func (*PendingIsZeroEntry) ProtoMessage()    {}
func (*PendingIsZeroEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebb505dd6f9ccdd, []int{2}
}
func (m *PendingIsZeroEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingIsZeroEntry.Unmarshal(m, b)
}
func (m *PendingIsZeroEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingIsZeroEntry.Marshal(b, m, deterministic)
}
func (m *PendingIsZeroEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingIsZeroEntry.Merge(m, src)
}
func (m *PendingIsZeroEntry) XXX_Size() int {
	return xxx_messageInfo_PendingIsZeroEntry.Size(m)
}
func (m *PendingIsZeroEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingIsZeroEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PendingIsZeroEntry proto.InternalMessageInfo

func (m *PendingIsZeroEntry) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *PendingIsZeroEntry) GetIsZero() bool {
	if m != nil {
		return m.IsZero
	}
	return false
}

// DenomCiphertext stores a ciphertext for a specific denom (used in MsgRotateKey).
type DenomCiphertext struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DenomCiphertext) Reset()         { *m = DenomCiphertext{} }
func (m *DenomCiphertext) String() string { return proto.CompactTextString(m) }
func (*DenomCiphertext) ProtoMessage()    {}
func (*DenomCiphertext) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebb505dd6f9ccdd, []int{3}
}
func (m *DenomCiphertext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DenomCiphertext.Unmarshal(m, b)
}
func (m *DenomCiphertext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DenomCiphertext.Marshal(b, m, deterministic)
}
func (m *DenomCiphertext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomCiphertext.Merge(m, src)
}
func (m *DenomCiphertext) XXX_Size() int {
	return xxx_messageInfo_DenomCiphertext.Size(m)
}
func (m *DenomCiphertext) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomCiphertext.DiscardUnknown(m)
}

var xxx_messageInfo_DenomCiphertext proto.InternalMessageInfo

func (m *DenomCiphertext) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *DenomCiphertext) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

// DenomProof stores a proof for a specific denom (used in MsgRotateKey).
type DenomProof struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Proof                []byte   `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DenomProof) Reset()         { *m = DenomProof{} }
func (m *DenomProof) String() string { return proto.CompactTextString(m) }
func (*DenomProof) ProtoMessage()    {}
func (*DenomProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebb505dd6f9ccdd, []int{4}
}
func (m *DenomProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DenomProof.Unmarshal(m, b)
}
func (m *DenomProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DenomProof.Marshal(b, m, deterministic)
}
func (m *DenomProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomProof.Merge(m, src)
}
func (m *DenomProof) XXX_Size() int {
	return xxx_messageInfo_DenomProof.Size(m)
}
func (m *DenomProof) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomProof.DiscardUnknown(m)
}

var xxx_messageInfo_DenomProof proto.InternalMessageInfo

func (m *DenomProof) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *DenomProof) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "nixprotocol.confidential.v1.Params")
	proto.RegisterType((*BalanceEntry)(nil), "nixprotocol.confidential.v1.BalanceEntry")
	proto.RegisterType((*PendingIsZeroEntry)(nil), "nixprotocol.confidential.v1.PendingIsZeroEntry")
	proto.RegisterType((*DenomCiphertext)(nil), "nixprotocol.confidential.v1.DenomCiphertext")
	proto.RegisterType((*DenomProof)(nil), "nixprotocol.confidential.v1.DenomProof")
}

func init() {
	proto.RegisterFile("nixprotocol/confidential/v1/types.proto", fileDescriptor_2ebb505dd6f9ccdd)
}

var fileDescriptor_2ebb505dd6f9ccdd = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x6b, 0x13, 0x41,
	0x14, 0xc6, 0x49, 0xdb, 0xa4, 0xed, 0xb3, 0x35, 0x66, 0x88, 0x74, 0x51, 0x90, 0x10, 0x50, 0x83,
	0x62, 0xd6, 0x2a, 0xa8, 0x57, 0x93, 0x4a, 0x95, 0x22, 0x2c, 0xab, 0xa7, 0x5e, 0x86, 0xd9, 0xdd,
	0x97, 0xcd, 0xd0, 0x9d, 0x79, 0xcb, 0xec, 0x6c, 0xdc, 0xcd, 0x1f, 0xee, 0x59, 0x76, 0xb2, 0x29,
	0xa9, 0x50, 0x0f, 0xde, 0x66, 0xbe, 0xdf, 0xf7, 0x7d, 0x3c, 0x1e, 0x0f, 0x5e, 0x6a, 0x59, 0xe5,
	0x86, 0x2c, 0xc5, 0x94, 0xf9, 0x31, 0xe9, 0x85, 0x4c, 0x50, 0x5b, 0x29, 0x32, 0x7f, 0x75, 0xee,
	0xdb, 0x3a, 0xc7, 0x62, 0xea, 0x30, 0x7b, 0xba, 0x63, 0x9c, 0xee, 0x1a, 0xa7, 0xab, 0xf3, 0x27,
	0xc3, 0x94, 0x52, 0x72, 0xd4, 0x6f, 0x5e, 0x9b, 0xc8, 0xf8, 0xf7, 0x1e, 0xf4, 0x02, 0x61, 0x84,
	0x2a, 0xd8, 0x0b, 0xe8, 0x8b, 0x32, 0x91, 0x96, 0x0c, 0xcf, 0xcb, 0x88, 0xdf, 0x60, 0xed, 0x75,
	0x46, 0x9d, 0xc9, 0x49, 0x78, 0xda, 0xca, 0x41, 0x19, 0x5d, 0x61, 0xcd, 0x7c, 0x18, 0xe6, 0x06,
	0x57, 0xfc, 0x6f, 0xf3, 0x9e, 0x33, 0x0f, 0x1a, 0xf6, 0xf9, 0x4e, 0xe0, 0x03, 0x9c, 0x6d, 0xbd,
	0x86, 0xac, 0xb0, 0x92, 0x34, 0x5f, 0xa2, 0x4c, 0x97, 0xd6, 0xdb, 0x1f, 0x75, 0x26, 0x07, 0xe1,
	0xe3, 0x16, 0x87, 0x2d, 0xfd, 0xea, 0x20, 0xfb, 0x08, 0xde, 0x36, 0x77, 0x83, 0x35, 0x4f, 0x8d,
	0x88, 0x91, 0xe7, 0x68, 0x24, 0x25, 0xde, 0xc1, 0x9d, 0xe0, 0x15, 0xd6, 0x97, 0x0d, 0x0d, 0x1c,
	0x64, 0xcf, 0xe1, 0x21, 0x6a, 0x11, 0x65, 0x98, 0xf0, 0x04, 0x35, 0xa9, 0xc2, 0xeb, 0x8e, 0xf6,
	0x27, 0xc7, 0xe1, 0x69, 0xab, 0x5e, 0x38, 0x91, 0xbd, 0x82, 0x81, 0x12, 0x15, 0xb7, 0x46, 0xe8,
	0x62, 0x81, 0x86, 0x47, 0xd2, 0x16, 0x5e, 0x6f, 0xd4, 0x99, 0x74, 0xc3, 0xbe, 0x12, 0xd5, 0xcf,
	0x56, 0x9f, 0x49, 0x5b, 0xb0, 0xd7, 0x30, 0xb8, 0x9d, 0x3d, 0x26, 0xca, 0x12, 0xfa, 0xa5, 0xbd,
	0x43, 0x37, 0xc4, 0xa3, 0x2d, 0x98, 0xb7, 0x3a, 0x1b, 0xc3, 0x69, 0x53, 0xac, 0x50, 0x11, 0x2f,
	0xe4, 0x1a, 0xbd, 0x23, 0x57, 0xfa, 0x40, 0x89, 0xea, 0x3b, 0x2a, 0xfa, 0x21, 0xd7, 0x38, 0xbe,
	0x80, 0x93, 0x99, 0xc8, 0x84, 0x8e, 0xf1, 0x8b, 0xb6, 0xa6, 0x66, 0x43, 0xe8, 0xba, 0x59, 0xdd,
	0xce, 0x8f, 0xc3, 0xcd, 0x87, 0x3d, 0x03, 0x88, 0x65, 0xbe, 0x44, 0x63, 0xb1, 0xb2, 0xed, 0x86,
	0x77, 0x94, 0xf1, 0x1c, 0x58, 0x80, 0x3a, 0x91, 0x3a, 0xfd, 0x56, 0x5c, 0xa3, 0xa1, 0x7f, 0x75,
	0x9d, 0xc1, 0xa1, 0x2c, 0xf8, 0x1a, 0x0d, 0xb9, 0xa2, 0xa3, 0xb0, 0x27, 0x5d, 0x66, 0x7c, 0x09,
	0x7d, 0xb7, 0x91, 0xf9, 0x6d, 0xef, 0x7f, 0x4e, 0xf3, 0x09, 0xc0, 0x15, 0x05, 0x86, 0x68, 0x71,
	0x4f, 0xc7, 0x10, 0xba, 0x79, 0x83, 0xdb, 0xf8, 0xe6, 0x33, 0x7b, 0x77, 0xfd, 0x36, 0x95, 0x76,
	0x59, 0x46, 0xd3, 0x98, 0x94, 0x7f, 0xdf, 0xbd, 0xbf, 0x51, 0x94, 0x94, 0x19, 0x6e, 0x6e, 0x3e,
	0xea, 0x39, 0xcf, 0xfb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x3e, 0x03, 0x12, 0x1f, 0x03,
	0x00, 0x00,
}
