// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nixprotocol/confidential/v1/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the module parameters.
type Params struct {
	AuditorPubKey        []byte   `protobuf:"bytes,1,opt,name=auditor_pub_key,json=auditorPubKey,proto3" json:"auditor_pub_key,omitempty"`
	MaxTransferBits      int32    `protobuf:"varint,6,opt,name=max_transfer_bits,json=maxTransferBits,proto3" json:"max_transfer_bits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebb505dd6f9ccdd, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAuditorPubKey() []byte {
	if m != nil {
		return m.AuditorPubKey
	}
	return nil
}

func (m *Params) GetMaxTransferBits() int32 {
	if m != nil {
		return m.MaxTransferBits
	}
	return 0
}

// BalanceEntry stores a ciphertext balance for a denomination.
type BalanceEntry struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceEntry) Reset()         { *m = BalanceEntry{} }
func (m *BalanceEntry) String() string { return proto.CompactTextString(m) }
func (*BalanceEntry) ProtoMessage()    {}
func (*BalanceEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebb505dd6f9ccdd, []int{1}
}
func (m *BalanceEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceEntry.Unmarshal(m, b)
}
func (m *BalanceEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceEntry.Marshal(b, m, deterministic)
}
func (m *BalanceEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceEntry.Merge(m, src)
}
func (m *BalanceEntry) XXX_Size() int {
	return xxx_messageInfo_BalanceEntry.Size(m)
}
func (m *BalanceEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceEntry.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceEntry proto.InternalMessageInfo

func (m *BalanceEntry) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *BalanceEntry) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

// PendingIsZeroEntry tracks whether a denom's pending balance is zero.
type PendingIsZeroEntry struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	IsZero               bool     `protobuf:"varint,2,opt,name=is_zero,json=isZero,proto3" json:"is_zero,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingIsZeroEntry) Reset()         { *m = PendingIsZeroEntry{} }
func (m *PendingIsZeroEntry) String() string { return proto.CompactTextString(m) }
func (*PendingIsZeroEntry) ProtoMessage()    {}
func (*PendingIsZeroEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebb505dd6f9ccdd, []int{2}
}
func (m *PendingIsZeroEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingIsZeroEntry.Unmarshal(m, b)
}
func (m *PendingIsZeroEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingIsZeroEntry.Marshal(b, m, deterministic)
}
func (m *PendingIsZeroEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingIsZeroEntry.Merge(m, src)
}
func (m *PendingIsZeroEntry) XXX_Size() int {
	return xxx_messageInfo_PendingIsZeroEntry.Size(m)
}
func (m *PendingIsZeroEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingIsZeroEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PendingIsZeroEntry proto.InternalMessageInfo

func (m *PendingIsZeroEntry) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *PendingIsZeroEntry) GetIsZero() bool {
	if m != nil {
		return m.IsZero
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "nixprotocol.confidential.v1.Params")
	proto.RegisterType((*BalanceEntry)(nil), "nixprotocol.confidential.v1.BalanceEntry")
	proto.RegisterType((*PendingIsZeroEntry)(nil), "nixprotocol.confidential.v1.PendingIsZeroEntry")
}

func init() {
	proto.RegisterFile("nixprotocol/confidential/v1/types.proto", fileDescriptor_2ebb505dd6f9ccdd)
}

var fileDescriptor_2ebb505dd6f9ccdd = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4b, 0xfb, 0x30,
	0x14, 0xc7, 0xe9, 0x96, 0x76, 0x59, 0xd8, 0x8f, 0xf5, 0x57, 0x04, 0x07, 0x82, 0x8c, 0x1d, 0x74,
	0x08, 0xb6, 0x4e, 0xff, 0x83, 0xa9, 0x07, 0xe3, 0x65, 0x14, 0x4f, 0xbb, 0x94, 0xb4, 0x7d, 0xdb,
	0x82, 0x4d, 0x52, 0x92, 0x74, 0xb4, 0x9e, 0xfc, 0xd3, 0x85, 0x6c, 0x87, 0x5e, 0xf4, 0x98, 0x4f,
	0x3e, 0xef, 0xfb, 0x1e, 0x5f, 0x72, 0x2b, 0x79, 0x5b, 0x6b, 0x65, 0x55, 0xa1, 0xaa, 0xa4, 0x50,
	0x72, 0xc7, 0x4b, 0x90, 0x96, 0xb3, 0x2a, 0x39, 0xae, 0x12, 0xdb, 0xd5, 0x60, 0x62, 0xf7, 0x1d,
	0x5d, 0xf5, 0xc4, 0xb8, 0x2f, 0xc6, 0xc7, 0xd5, 0xe2, 0xdb, 0x23, 0xc1, 0x86, 0x69, 0x26, 0x4c,
	0x74, 0x43, 0xa6, 0xac, 0x29, 0xb9, 0x55, 0x3a, 0xab, 0x9b, 0x3c, 0xfb, 0x84, 0x6e, 0xe6, 0xcd,
	0xbd, 0xe5, 0x24, 0xfd, 0x77, 0xc6, 0x9b, 0x26, 0x7f, 0x87, 0x2e, 0xba, 0x23, 0xff, 0x05, 0x6b,
	0x33, 0xab, 0x99, 0x34, 0x3b, 0xd0, 0x59, 0xce, 0xad, 0x99, 0x05, 0x73, 0x6f, 0xe9, 0xa7, 0x53,
	0xc1, 0xda, 0x8f, 0x33, 0x5f, 0x73, 0x6b, 0x28, 0xc2, 0x83, 0x70, 0x48, 0x11, 0x1e, 0x86, 0x88,
	0x22, 0x8c, 0x42, 0x9f, 0x22, 0xec, 0x87, 0x01, 0x45, 0x78, 0x14, 0x62, 0x8a, 0x30, 0x0e, 0xc7,
	0x8b, 0x17, 0x32, 0x59, 0xb3, 0x8a, 0xc9, 0x02, 0x5e, 0xa5, 0xd5, 0x5d, 0x74, 0x41, 0xfc, 0x12,
	0xa4, 0x12, 0x6e, 0xfb, 0x38, 0x3d, 0x3d, 0xa2, 0x6b, 0x42, 0x0a, 0x5e, 0x1f, 0x40, 0x5b, 0x68,
	0xed, 0x6c, 0xe0, 0x0e, 0xeb, 0x91, 0xc5, 0x33, 0x89, 0x36, 0x20, 0x4b, 0x2e, 0xf7, 0x6f, 0x66,
	0x0b, 0x5a, 0xfd, 0x95, 0x75, 0x49, 0x46, 0xdc, 0x64, 0x5f, 0xa0, 0x95, 0x0b, 0xc2, 0x69, 0xc0,
	0xdd, 0xcc, 0xfa, 0x71, 0xfb, 0xb0, 0xe7, 0xf6, 0xd0, 0xe4, 0x71, 0xa1, 0x44, 0xf2, 0x5b, 0xc1,
	0xf7, 0x42, 0x95, 0x4d, 0x05, 0xa7, 0x92, 0xf3, 0xc0, 0x39, 0x4f, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xe1, 0xb0, 0xbd, 0x5c, 0x90, 0x01, 0x00, 0x00,
}
