syntax = "proto3";
package nixprotocol.confidential.v1;

option go_package = "github.com/nixprotocol/confidential-module/types";

import "nixprotocol/confidential/v1/types.proto";

message GenesisState {
  Params params = 1;
  repeated AccountState accounts = 2;
}

message AccountState {
  string address = 1;
  bytes pubkey = 2;
  uint32 key_counter = 3;
  repeated BalanceEntry available_balances = 4;
  repeated BalanceEntry pending_balances = 5;
  repeated PendingIsZeroEntry pending_is_zero = 6;
  uint64 rotation_height = 7;
}
